### ISSUE TITLE
crane load description

### ISSUE THREAD

**Issue by ejri** [P8sx/crane-scale#1]
Hey, for the crane load, what does the wheatbridge circuit connection look like with the HX711 look like?

Have you tried connecting this to HA via esphome? 
https://esphome.io/components/sensor/hx711.html

**Comment by P8sx** [comment]
It's a standard connection according to used load cell diagram and output from HX711 connected to any non strapping pin to ESP

And connection to HA, sure it is possible but was not in scope of this project
